import { AgentDefinition } from "@/lib/agents/types";

export const agentCatalog: AgentDefinition[] = [
  {
    id: "product",
    name: "Product AI",
    role: "Senior Product Manager",
    responsibility: "Translate user intent into requirements, stories, and acceptance criteria.",
    expertise: ["PRD", "Roadmaps", "Backlog", "Sprint planning"],
    dependencies: [],
    toolPermissionTier: "read-only",
  },
  {
    id: "research",
    name: "Research AI",
    role: "Technical Researcher",
    responsibility: "Evaluate technologies, best practices, and implementation options.",
    expertise: ["Framework comparison", "Libraries", "Best practices"],
    dependencies: [],
    toolPermissionTier: "read-only",
  },
  {
    id: "architect",
    name: "Architect AI",
    role: "Senior Software Architect",
    responsibility: "Design system boundaries, APIs, and project structure.",
    expertise: ["System design", "Scalability", "Auth strategy", "API design"],
    dependencies: ["product", "research"],
    toolPermissionTier: "read-only",
  },
  {
    id: "uiux",
    name: "UI/UX AI",
    role: "Senior Product Designer",
    responsibility: "Design user flows, wireframes, and component systems.",
    expertise: ["Wireframes", "Accessibility", "Design systems"],
    dependencies: ["product"],
    toolPermissionTier: "read-only",
  },
  {
    id: "database",
    name: "Database AI",
    role: "Database Engineer",
    responsibility: "Design schemas, relationships, and query paths.",
    expertise: ["Prisma", "PostgreSQL", "Normalization", "Indexes"],
    dependencies: ["architect"],
    toolPermissionTier: "writer",
  },
  {
    id: "backend",
    name: "Backend AI",
    role: "Senior Backend Engineer",
    responsibility: "Implement APIs, business logic, and security foundations.",
    expertise: ["Node.js", "APIs", "Auth", "Service architecture"],
    dependencies: ["architect", "database"],
    toolPermissionTier: "writer",
  },
  {
    id: "frontend",
    name: "Frontend AI",
    role: "Senior Frontend Engineer",
    responsibility: "Build pages, components, client state, and interactions.",
    expertise: ["Next.js", "React", "Tailwind", "Accessibility"],
    dependencies: ["architect", "uiux"],
    toolPermissionTier: "writer",
  },
  {
    id: "mobile",
    name: "Mobile AI",
    role: "Senior Mobile Engineer",
    responsibility: "Build mobile clients when requested by product scope.",
    expertise: ["React Native", "Flutter", "Swift", "Kotlin"],
    dependencies: ["architect", "uiux"],
    toolPermissionTier: "writer",
  },
  {
    id: "security",
    name: "Security AI",
    role: "Cybersecurity Engineer",
    responsibility: "Audit vulnerabilities and enforce secure defaults.",
    expertise: ["OWASP", "Auth review", "Dependency audits"],
    dependencies: ["backend", "database", "frontend"],
    toolPermissionTier: "reviewer",
  },
  {
    id: "performance",
    name: "Performance AI",
    role: "Performance Engineer",
    responsibility: "Profile and optimize runtime, queries, and bundle behavior.",
    expertise: ["Profiling", "Caching", "Bundle analysis", "Query tuning"],
    dependencies: ["backend", "frontend", "database"],
    toolPermissionTier: "reviewer",
  },
  {
    id: "qa",
    name: "QA AI",
    role: "Quality Assurance Engineer",
    responsibility: "Generate and run test plans across layers.",
    expertise: ["Unit tests", "Integration tests", "E2E", "Regression"],
    dependencies: ["backend", "frontend"],
    toolPermissionTier: "reviewer",
  },
  {
    id: "documentation",
    name: "Documentation AI",
    role: "Technical Writer",
    responsibility: "Generate and maintain technical and user-facing documentation.",
    expertise: ["README", "API docs", "Guides", "Changelog"],
    dependencies: ["product", "architect", "backend", "frontend", "qa"],
    toolPermissionTier: "writer",
  },
  {
    id: "devops",
    name: "DevOps AI",
    role: "DevOps Engineer",
    responsibility: "Prepare deployment, CI/CD, and infrastructure automation.",
    expertise: ["Docker", "CI/CD", "Vercel", "Cloud deployment"],
    dependencies: ["backend", "frontend", "qa", "security", "performance"],
    toolPermissionTier: "reviewer",
  },
];
